name: command-listener

on:
  issue_comment:
    types: ["created"]

jobs:
  action_pr_comment:
    name: Action PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch
        id: dispatch
        env:
          USER: ${{ github.event.sender.login }}
          ALLOWED_USERS: ${{ join(fromJson('["ThetaSinner", "jost-s", "maackle", "thedavidmeister", "steveej", "neonphog", "matthme", "c12i"]'), '\n') }}
          COMMENT: ${{ github.event.comment.body }}
        run: |
          set -euo pipefail
          
          if echo "$ALLOWED_USERS" | grep -q "^${USER}$"; then
            echo "User $USER is allowed to run commands"
          else
            echo "User $USER is not allowed to run commands"
            exit 1
          fi
          
          COMMAND=""
          if [[ "$COMMENT" == @hra* ]]; then
            echo "Comment is a command"
            COMMAND=$(echo "$COMMENT" | cut -b 6- | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
          fi
          
          echo "Setting command '$COMMAND'"
          
          echo "action=${COMMAND}" >> "$GITHUB_OUTPUT"
    outputs:
      action: ${{ steps.dispatch.outputs.action }}
  flake_update:
    name: Flake update
    runs-on: ubuntu-latest
    needs: [action_pr_comment]
    if: ${{ startsWith(needs.action_pr_comment.outputs.action, 'flake_update') }}
    steps:
      - name: Configure
        env:
          ACTION: ${{ needs.action_pr_comment.outputs.action }}
          NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.HRA_GITHUB_TOKEN }}
        run: |
          HOLONIX_VERSION=$(echo $ACTION | cut -b 14- | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
          gh pr comment $NUMBER -b "Got it, will try to update inputs for Holonix version $HOLONIX_VERSION"
        
